 --PERMISOS MAGNOS3--
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON cliente TO Magnos1,Magnos2,Magnos4;
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON fragmentoEmpleado TO Magnos1,Magnos2,Magnos4;
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON fragmentoHotel TO Magnos1,Magnos2,Magnos4 ;
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON fragmentoTrabaja TO Magnos1,Magnos2,Magnos4;
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON fragmentoReserva TO Magnos1,Magnos2,Magnos4 ;
