--PERMISOS MAGNOS2--
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON cliente TO Magnos1,Magnos3,Magnos4;
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON fragmentoEmpleado TO Magnos1,Magnos3,Magnos4 ;
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON fragmentoHotel TO Magnos1,Magnos3,Magnos4 ;
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON fragmentoTrabaja TO Magnos1,Magnos3,Magnos4;
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON fragmentoProveedor TO Magnos1,Magnos3,Magnos4 ;
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON fragmentoReserva TO Magnos1,Magnos3,Magnos4 ;
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON fragmentoTiene TO Magnos1,Magnos3,Magnos4 ;
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON fragmentoSuministro TO Magnos1,Magnos3,Magnos4 ;
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON articulo TO Magnos1,Magnos3,Magnos4 ;
