 --PERMISOS MAGNOS1--
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON cliente TO Magnos2,Magnos3,Magnos4;
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON fragmentoEmpleado TO Magnos2,Magnos3,Magnos4;
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON fragmentoHotel TO Magnos2,Magnos3,Magnos4;
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON fragmentoTrabaja TO Magnos2,Magnos3,Magnos4;
GRANT SELECT,UPDATE,DELETE,INSERT,REFERENCES ON fragmentoReserva TO Magnos2,Magnos3,Magnos4 ;
